spring:
  profiles:
    active: prod
  datasource:
    url: .
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: .
    password: .

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jwt:
    secret: .
